"""empty message

Revision ID: 03195b113cd1
Revises: 4039d93e55a6
Create Date: 2020-12-05 14:37:34.343038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03195b113cd1'
down_revision = '4039d93e55a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
