"""empty message

Revision ID: aa8987e75e45
Revises: 23beaeace28a
Create Date: 2020-12-01 14:52:13.025190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa8987e75e45'
down_revision = '23beaeace28a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #We changed nullable=False to true
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))
    #executed an update to the table saying where there isn't a value for the column
    op.execute('UPDATE todos SET completed = False WHERE completed IS NULL;')
    # Update the column again and sets nullable to false
    op.alter_column('todos', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
